// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC24OOnmfhOJQWvtptRrRxHbSlVKy-7pdQ',
    appId: '1:565408257461:web:d5c4de6bcdf994bef875fc',
    messagingSenderId: '565408257461',
    projectId: 'smartfit-aa6ce',
    authDomain: 'smartfit-aa6ce.firebaseapp.com',
    storageBucket: 'smartfit-aa6ce.appspot.com',
    measurementId: 'G-B20VP7Y24J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfosFZLWYBfU6OZu2wOU29dBXDkvBAypQ',
    appId: '1:565408257461:android:58752f453f777973f875fc',
    messagingSenderId: '565408257461',
    projectId: 'smartfit-aa6ce',
    storageBucket: 'smartfit-aa6ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOySWGASbeQ-M2H_fqn8htZyssRG6eMyk',
    appId: '1:565408257461:ios:0c226a21e5ebe941f875fc',
    messagingSenderId: '565408257461',
    projectId: 'smartfit-aa6ce',
    storageBucket: 'smartfit-aa6ce.appspot.com',
    iosClientId: '565408257461-bjjmbapjdpjbqb80q24eme1gj0kcgc62.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOySWGASbeQ-M2H_fqn8htZyssRG6eMyk',
    appId: '1:565408257461:ios:5d744bb3fe9fbd46f875fc',
    messagingSenderId: '565408257461',
    projectId: 'smartfit-aa6ce',
    storageBucket: 'smartfit-aa6ce.appspot.com',
    iosClientId: '565408257461-le8350d5ra0a5295c6sbq2n9ue4it1oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFit.RunnerTests',
  );
}
